FROM golang:1.25.0-bookworm AS base
RUN apt-get update -y && apt-get install -y git
WORKDIR /go/d-voting
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
ENV GOCACHE=/root/.cache/go-build
WORKDIR /go/d-voting/cli/dvoting
RUN --mount=type=cache,target="/root/.cache/go-build" go install
# DELA is part of the D-Voting module and is built from this checkout.
WORKDIR /go/d-voting
RUN --mount=type=cache,target="/root/.cache/go-build" go install ./dela/cli/crypto

FROM golang:1.25.0-bookworm AS build
WORKDIR /usr/local/bin
COPY --from=base /go/bin/crypto .
COPY --from=base /go/bin/dvoting .
ENTRYPOINT ["/bin/bash", "-c", "dvoting --config /data/node start --postinstall --proxyaddr :$PROXYPORT --proxykey $PROXYKEY --listen tcp://0.0.0.0:2000 --public $PUBLIC_URL --routing tree --noTLS"]
CMD []
