name: Go Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: TestIntegration
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Run the integration test
        run: go test -timeout 10m -run TestIntegration ./integration/... 
  test:
    name: TestBadVote
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run the bad vote test
        run: go test -timeout 10m -run TestBadVote ./integration/...
  test:
    name: TestCrash
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        
      - name: Run the crash test
        run: go test -timeout 10m -run TestCrash ./integration/...
  test:
    name: TestRevote
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run the revote test
        run: go test -timeout 10m -run TestRevote ./integration/...





