name: Go Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
<<<<<<< HEAD
=======

>>>>>>> 1cfffaf (fix github action)
  integration:
    name: Test Integration
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run the integration test
<<<<<<< HEAD
        run: go test -timeout 10m -run TestIntegration ./integration/...
=======
        run: go test -timeout 10m -run TestIntegration ./integration/... 
>>>>>>> 1cfffaf (fix github action)
  bad_vote:
    name: Test bad vote
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run the bad vote test
        run: go test -timeout 10m -run TestBadVote ./integration/...
  crash:
    name: Test crash
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run the crash test
        run: go test -timeout 10m -run TestCrash ./integration/...
  revote:
    name: Test revote
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run the revote test
        run: go test -timeout 10m -run TestRevote ./integration/...
