name: Go lint DELA

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-dela:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Lint DELA
        run: make lint-dela
