name: Go Unit Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Use Go 1.25
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      # Legacy DELA used golangci-lint, but 70 files in d-voting fail it.
      # TODO: re-enable golangci-lint once those issues are resolved.
      - name: Run lint
        run: make lint

      - name: Run vet
        run: make vet

      - name: Test all, except integration, with coverage
        run: |
          go test $(go list ./... | grep -v /integration)
